FROM node:14-alpine as build

WORKDIR /usr/src/indexer-tree
COPY ["package.json", "yarn.lock", "./"]
RUN yarn install
COPY . /usr/src/indexer-tree
RUN yarn run build


FROM node:14-alpine

ENV APP_DOCKER TRUE
ENV NODE_ENV production
WORKDIR /usr/src/indexer-tree
COPY ["package.json", "yarn.lock", "./"]
RUN yarn install --production
USER node
COPY --chown=node:node --from=build /usr/src/indexer-tree/dist /usr/src/indexer-tree
EXPOSE 3000
CMD [ "node", "main" ] 