version: '3'

services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASS}
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - dbs

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    ports:
      - ${MONGO_PORT}:27017
    networks:
      - dbs

networks:
  dbs:
    driver: bridge
